manifest:
  remotes:
    - name: wizarddata
      url-base: https://github.com/wizarddata
  projects:
    - name: zmk
      remote: badjeff
      revision: pointers-with-input-processors
      import: app/west.yml
    - name: zmk
      remote: wizarddata
      revision: Ergo_S-1_OE
  self:
    path: config
